#!/usr/bin/env python

import argparse
import sys
import subprocess
import os

from app_controllers.nginx_controller import handle_nginx
from app_controllers.uwsgi_controller import handle_uwsgi

if os.getuid():
    sys.stderr.write("Error. Plese start ksc with root privileges\n")
    exit(1)

parser = argparse.ArgumentParser(
    description="The Knowledge Sharing Campaign Web App.")
parser.add_argument(
    "-start", help="Render configs and start all the services.", action='store_true')
parser.add_argument(
    "-stop", help="Stop all services and clean up.", action='store_true')
parser.add_argument("-restart", help="Restart the app", action='store_true')
parser.add_argument(
    "--port", help="Specify the port to listen to. Default is 7070", type=int, default=7070)
args = parser.parse_args()

if not(args.start or args.stop or args.restart):
    sys.stderr.write(
        "Error. Please specify one option among (-start, -stop, -restart)\n")
    exit(1)

if args.start:
    mode = "start"
elif args.stop:
    mode = "stop"
else:
    mode = "restart"

handle_nginx(mode, args.port)
handle_uwsgi(mode)
