#!/usr/bin/env python

import argparse
import sys
import subprocess
import os

if os.getuid():
    sys.stderr.write("Error. Plese start ksc with root privileges\n")
    exit(1)

parser = argparse.ArgumentParser(
    description="The Knowledge Sharing Campaign Web App.")
parser.add_argument(
    "-start", help="Render configs and start all the services.", action='store_true')
parser.add_argument(
    "-stop", help="Stop all services and clean up.", action='store_true')
parser.add_argument("-restart", help="Restart the app", action='store_true')
parser.add_argument(
    "--port", help="Specify the port to listen to. Default is 7070", type=int, default=7070)
args = parser.parse_args()

if not(args.start or args.stop or args.restart):
    sys.stderr.write(
        "Error. Please specify one option among (-start, -stop, -restart)\n")
    exit(1)

if args.start:
    mode = "start"
elif args.stop:
    mode = "stop"
else:
    mode = "restart"

nginx_pid_file = ".NGINX_PID"


def render_nginx_config():
    print "Rendering config for nginx..."
    subprocess.call(['node', 'render_conf.js', str(args.port)])
    print "Config rendered."


def kill_nginx():
    if os.path.exists(nginx_pid_file):
        print "Running nginx process found. Killing it..."
        with open(nginx_pid_file) as pid:
            subprocess.call(['kill', pid.readlines()[0].strip()])
        os.remove(nginx_pid_file)
        print "nginx stopped."


def start_nginx():
    render_nginx_config()

    print "Starting nginx..."
    kill_nginx()

    process = subprocess.Popen(
        ["nginx", "-c", os.getcwd() + "/app/server_configs/nginx.conf"])

    process.wait()
    if process.poll() != 0:
        print "nginx start failed."
    else:
        with open(nginx_pid_file, "w") as pid:
            pid.write(str(process.pid + 1))  # TODO: Possibly flaky PID check.
        print "nginx successfully started on port %d" % args.port


def handle_nginx(mode):
    if mode == "start":
        start_nginx()
    elif mode == "stop":
        kill_nginx()
    else:
        kill_nginx()
        start_nginx()

handle_nginx(mode)
